version: '3.5'

services:
  user_service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - "./domain/src/:/usr/local/domain/src/"
      - "./user_service/src/:/usr/local/app/src/"
